- name: build docker images
  hosts: localhost
  vars_files:
  - docker-vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: 'https://github.com/geneontology/{{ item.key }}.git'
     dest: ./{{ item.key }}
     version: '{{ item.value }}'
     force: yes 
    loop: '{{ repo_map|dict2items }}'

  - name: build golr container image
    shell: "docker build -f docker/Dockerfile.golr -t '{{ docker_hub_user }}/golr:{{ tag }}' amigo"

  - name: build noctua container image
    shell: "docker build -f docker/Dockerfile.noctua -t '{{ docker_hub_user }}/noctua:{{ noctua_tag }}' noctua"

  - name: build minerva container image
    shell: "docker build -f docker/Dockerfile.minerva -t '{{ docker_hub_user }}/minerva:{{ minerva_tag }}' minerva"
